CREATE SCHEMA IF NOT EXISTS securecapita;

SET NAMES 'UTF8MB4';
SET TIME_ZONE = '-4:00';

USE securecapita;

CREATE TABLE Users
(
	id 				BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	first_name  	VARCHAR(50) NOT NULL,
	last_name   	VARCHAR(50) NOT NULL,
	email 			VARCHAR(100) NOT NULL,
	password 		VARCHAR(255) DEFAULT NULL,
	address 		VARCHAR(255) DEFAULT NULL,
	phone 			VARCHAR(30) DEFAULT NULL,
	title 			VARCHAR(50) DEFAULT NULL,
	bio 			VARCHAR(255) DEFAULT NULL,
	enabled 		BOOLEAN DEFAULT FALSE,
	non_locked 		BOOLEAN DEFAULT TRUE,
	using_mfa 		BOOLEAN DEFAULT FALSE,
	created_date 	DATETIME DEFAULT CURRENT_TIMESTAMP,
	image_url 		VARCHAR(255) DEFAULT 'https://images.unsplash.com/photo-1617975251517-b90ff061b52e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cHJvZmlsZSUyMGltYWdlfGVufDB8MXwwfHx8MA%3D%3D',
	CONSTRAINT UQ_Users_Email UNIQUE (email)
	
);

CREATE TABLE Roles
(
	id 				BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name  			VARCHAR(50) NOT NULL,
	permission   	VARCHAR(255) NOT NULL,
	CONSTRAINT UQ_Roles_Name UNIQUE (name)
);

CREATE TABLE UserRoles
(
	id 	BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	role_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (role_id) REFERENCES Roles (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT UQ_UserRoles_User_Id UNIQUE (user_id)
);

CREATE TABLE Events
(
	id 	BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type  			VARCHAR(50) NOT NULL,
	description   	VARCHAR(255) NOT NULL,
	CONSTRAINT UQ_Events_Type UNIQUE (type)
);

CREATE TABLE UserEvents
(
	id 				BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id  		BIGINT UNSIGNED NOT NULL,
	event_id   		BIGINT UNSIGNED NOT NULL,
	device 			VARCHAR(100) DEFAULT NULL,
	ip_address 		VARCHAR(100) DEFAULT NULL,
	created_at		DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (event_id) REFERENCES Events (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE AccountVerifications
(
	id 			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id  	BIGINT UNSIGNED NOT NULL,
	url  		VARCHAR(255) NOT NULL,
	-- date		DATETIME NOT NULL,	
	FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT UQ_AccountVerifications_User_Id UNIQUE (user_id),
	CONSTRAINT UQ_AccountVerifications_Url UNIQUE (url)
	
);

CREATE TABLE ResetPasswordVerifications
(
	id 					BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id  			BIGINT UNSIGNED NOT NULL,
	url  				VARCHAR(255) NOT NULL,
	expiration_date		DATETIME NOT NULL,	
	FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT UQ_ResetPasswordVerifications_User_Id UNIQUE (user_id),
	CONSTRAINT UQ_ResetPasswordVerifications_Url UNIQUE (url)
	
);

CREATE TABLE TwoFactorVerifications
(
	id 					BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id  			BIGINT UNSIGNED NOT NULL,
	code  				VARCHAR(10) NOT NULL,
	expiration_date		DATETIME NOT NULL,	
	FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT UQ_TwoFactorVerifications_User_Id UNIQUE (user_id),
	CONSTRAINT UQ_TwoFactorVerifications_Code UNIQUE (code)
	
);

